sprint1/src/Entity/Entretien.php
<?php

namespace App\Entity;

use App\Repository\EntretienRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EntretienRepository::class)
 */
class Entretien
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Dateentretien;

    /**
     * @ORM\Column(type="integer")
     */
    private $Idevaluation;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $idParticipant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateentretien(): ?string
    {
        return $this->Dateentretien;
    }

    public function setDateentretien(string $Dateentretien): self
    {
        $this->Dateentretien = $Dateentretien;

        return $this;
    }

    public function getIdEvaluation(): ?int
    {
        return $this->Idevaluation;
    }

    public function setIdEvaluation(int $Idevaluation): self
    {
        $this->Idevaluation = $Idevaluation;

        return $this;
    }

    public function getIdParticipant(): ?int
    {
        return $this->idParticipant;
    }

    public function setIdParticipant(int $idParticipant): self
    {
        $this->idParticipant = $idParticipant;

        return $this;
    }
}

sprint1/src/Entity/Evaluation.php
<?php

namespace App\Entity;

use App\Repository\EvaluationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvaluationRepository::class)
 */
class Evaluation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Dateevaluation;

    /**
     * @ORM\Column(type="integer")
     */
    private $idEntreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateevaluation(): ?string
    {
        return $this->Dateevaluation;
    }

    public function setDateevaluation(string $Dateevaluation): self
    {
        $this->Dateevaluation = $Dateevaluation;

        return $this;
    }

    public function getIdEntreprise(): ?int
    {
        return $this->idEntreprise;
    }

    public function setIdEntreprise(int $idEntreprise): self
    {
        $this->idEntreprise = $idEntreprise;

        return $this;
    }
}

sprint1/src/Controller/EvaluationController.php
<?php

namespace App\Controller;
use App\Entity\Evaluation;
use App\Entity\ParticipationEvaluation;
use App\Entity\Quiz;
use App\Entity\Utilisateur;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class EvaluationController extends AbstractController
{
    /**
     * @Route("/evaluation", name="evaluation")
     */
    public function index(): Response
    {
        $class = $this->getDoctrine()->getRepository(Evaluation::class)->findAll();
        return $this->render('evaluation/list.html.twig', ['classe'=>$class]);
    }

    /**
     * @Route("/evaluationF", name="evaluationF")
     */
    public function listF(): Response
    {
        $class = $this->getDoctrine()->getRepository(Evaluation::class)->findAll();
        $participation = $this->getDoctrine()->getRepository(ParticipationEvaluation::class)->findAll();
        return $this->render('evaluation/listF.html.twig', ['classe'=>$class,'participation'=>$participation]);
    }


    /**
     * @Route("/afficherParticipants", name="afficherParticipants")
     */
    public function listparticipants(): Response
    {
        $class = $this->getDoctrine()->getRepository(Evaluation::class)->findAll();
        return $this->render('evaluation/participants.html.twig', ['classe'=>$class]);
    }
    /**
     * @Route("/afficherQuiz", name="afficherQuiz")
     */
    public function listquiz(): Response
    {
        $class = $this->getDoctrine()->getRepository(Evaluation::class)->findAll();
        return $this->render('evaluation/quiz.html.twig', ['classe'=>$class]);
    }

    /**
     * @Route("/ajouterEvaluation", name="ajouterEvaluation")
     */
    public function createEvaluation(Request $request)
    {
        if ($request->request->count()>0)
        {
            $evaluation=new Evaluation();
            $evaluation->setLibelle($request->get('Libelle'));
            $evaluation->setDescription($request->get('Description'));
            $evaluation->setDateevaluation($request->get('Dateevaluation'));
            $evaluation->setIdEntreprise($request->get('Identreprise'));
            $em=$this->getDoctrine()->getManager();
            $em->persist($evaluation);
            $em->flush();
            return $this->redirectToRoute('evaluation');
        }
        $entreprise=$this->getDoctrine()->getRepository(Utilisateur::class)->findAll();
        return $this->render('evaluation/add.html.twig',['classe'=>$entreprise]);
    }

    /**
     * @Route("/modifierEvaluation/{id}", name="modifierEvaluation")
     */
    public function updateEvaluation(Request $request,$id)
    {
        if ($request->request->count()>0)
        {
            $em=$this->getDoctrine()->getManager();
            $evaluation=$em->getRepository(Evaluation::class)->find($id);
            $evaluation->setLibelle($request->get('Libelle'));
            $evaluation->setDescription($request->get('Description'));
            $evaluation->setDateevaluation($request->get('Dateevaluation'));
            $evaluation->setIdEntreprise($request->get('Identreprise'));
            $em->flush();
            return $this->redirectToRoute('evaluation');
        }
        $evaluation=$this->getDoctrine()->getRepository(Evaluation::class)->find($id);
        $entreprise=$this->getDoctrine()->getRepository(Utilisateur::class)->findAll();
        return $this->render('evaluation/update.html.twig', ['evaluation'=>$evaluation,'classe'=>$entreprise]);
    }

    /**
     * @Route("/supprimerEvaluation/{id}",name="supprimerEvaluation")
     */
    public function deleteEvaluation($id)
    {
        $em = $this->getDoctrine()->getManager();
        $class = $this->getDoctrine()->getRepository(Evaluation::class)->find($id);
        $em->remove($class);
        $em->flush();
        return $this->redirectToRoute('evaluation');
    }

    /**
     * @Route("/pdfEvaluation/{id}/{libelle}/{description}/{dateevaluation}/{identreprise}",name="pdfEvaluation")
     */
    public function pdf($id,$libelle,$description,$dateevaluation,$identreprise)
    {
        $mdpdf = new \Mpdf\Mpdf();

        //Contenu du PDF
        $data= "";


        $data.="<h1>Votre Evaluation</h1>";

        $data.="<strong>ID Evaluation : </strong> " . $id . "<br>";
        $data.="<strong>libelle Evaluation : </strong> " . $libelle . "<br>";
        $data.="<strong>Description Evaluation : </strong> " . $description . "<br>";
        $data.="<strong>Date Dvaluation : </strong> " . $dateevaluation . "<br>";
        $data.="<strong>ID Entreprise : </strong>" . $identreprise . "<br>";

        $quiz = $this->getDoctrine()->getRepository(Quiz::class)->findall();
        $data.="<h2>Vos Questions du quiz</h2>";
        $cmp=0;
        foreach ($quiz as $q)
        {
            if($q->getIdEvaluation()==$id)
            {
                $data .= "<strong>Question$cmp : </strong> " . $q->getQuestion() . "<br>";
                $data .= "<strong>Choix1 : </strong> " . $q->getChoix1() . "<br>";
                $data .= "<strong>Choix2 : </strong> " . $q->getChoix2() . "<br>";
                $data .= "<strong>Choix3 : </strong> " . $q->getChoix3() . "<br><br>";
            }
        }

        //Création du PDF
        $mdpdf->WriteHTML($data);

        //Téléchargement du PDF
        $mdpdf->Output("Evaluation N".$id.".pdf","D");

        return $this->redirectToRoute('evaluation');
    }



}

sprint1/templates/evaluation/add.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajouter Evaluation</title>
</head>
<body>

<br>
<br>
<br>

<div class="pd-20 card-box mb-30">
    <h2>Créer une Evaluation</h2> <br> <br>
    <div class="clearfix">
    </div>
<form action="" method="POST" name="form" id="form">
    Libelle <input class="form-control form-control-sm form-control-line" type="text" placeholder="Libelle" name="Libelle" id="Libelle">
    <br>
    Description <input class="form-control form-control-sm form-control-line" type="text" placeholder="Description" name="Description" id="Description">
    <br>
    Date Evaluation <input class="form-control form-control-sm form-control-line" placeholder="Date Evaluation" name="Dateevaluation" id="Dateevaluation" value="{{  date("now")| date("m-d-Y") }}" readonly>

    <br>
    Id Entreprise <select class="custom-select col-12" name="Identreprise">
        {% for Entreprise in classe %}
            <option value={{ Entreprise.Id }}>{{ Entreprise.Id }}</option>
        {% endfor %}
    </select>
    <br>
    <br>
    <br>
    <button class="btn btn-outline-primary" type="button" id="accept" onclick="ControlSaisie()">Ajouter Evaluation</button>
</form>
</div>
</body>
</html>
    <script>
        function isValidDate2(dateString)
        {
            /*var parts = dateString.split("-");
            var day = parseInt(parts[1], 10);
            var month = parseInt(parts[0], 10);
            var year = parseInt(parts[2], 10);

            var today = new Date();
            var today_x = today.getFullYear()*10000+(today.getMonth()+1)*100+today.getDate();
            var date_x = year*10000 + month*100 + day;
            return date_x > today_x;*/
            return true;
        }

        function isValidDate(dateString)
        {
            if(!/^\d{1,2}\-\d{1,2}\-\d{4}$/.test(dateString))
                return false;

            var parts = dateString.split("-");
            var day = parseInt(parts[1], 10);
            var month = parseInt(parts[0], 10);
            var year = parseInt(parts[2], 10);

            if(year < 1000 || year > 3000 || month == 0 || month > 12)
                return false;

            var monthLength = [ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 ];

            if(year % 400 == 0 || (year % 100 != 0 && year % 4 == 0))
                monthLength[1] = 29;

            return day > 0 && day <= monthLength[month - 1];
        }
            function ControlSaisie() {
                var Libelle = document.getElementById("Libelle").value;
                var Description = document.getElementById("Description").value;
                var DateE = document.getElementById("Dateevaluation").value;

                    if (Libelle !== "" && Libelle != null) {
                        if (Description != null && Description !== "") {
                            if (DateE != null && DateE !== "" && isValidDate(DateE) && isValidDate2(DateE)) {
                                //c bon
                            } else {
                                alert("Le Champ Date Evaluation n'est pas valide!");
                                return false;
                            }
                        } else {
                            alert("Le Champ Description est vide!");
                            return false
                        }
                    } else {
                        alert("Le Champ Libelle est vide!");
                        return false;
                    }
                    document.getElementById("form").submit();
                    return true;
            }
    </script>
{% endblock %}

sprint1/templates/evaluation/addP.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajouter Participation au Evaluation</title>
</head>
<body>

<br>
<br>
<br>

<div class="pd-20 card-box mb-30">
    <h2>Créer Participation au Evaluation</h2> <br> <br>
    <div class="clearfix">

    </div>
<form action="" method="POST" name="form" id="form">
    ID Evaluation <input class="form-control form-control-sm form-control-line" type="text" placeholder="id Evaluation" name="idE" readonly value={{ Evaluation.id }}>
    <br>
    ID Participant <select class="custom-select col-12" name="idP">
        {% for Utilisateur in classe %}
            <option value={{ Utilisateur.Id }}>{{ Utilisateur.Id }}</option>
        {% endfor %}
    </select>
    <br>
    <br>
    <br>
    <button class="btn btn-outline-primary" type="submit">Ajouter Participant</button>
</form>
</div>
</body>
</html>
{% endblock %}

sprint1/templates/evaluation/addQ.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Ajouter Question du Quiz au Evaluation</title>
    </head>
    <body>

    <br>
    <br>
    <br>

    <div class="pd-20 card-box mb-30">
        <h2>Créer Question du Quiz</h2> <br> <br>
        <div class="clearfix">

        </div>
        <form action="" method="POST" name="form" id="form">
            ID Evaluation <input class="form-control form-control-sm form-control-line" type="text" placeholder="id Evaluation" name="idE" readonly value={{ Evaluation.id }}>
            <br>
            Question <input class="form-control form-control-sm form-control-line" type="text" placeholder="Question" name="Question" id="Question">
            <br>
            Choix1 <input class="form-control form-control-sm form-control-line" type="text" placeholder="Choix1" name="Choix1" id="Choix1">
            <br>
            Choix2 <input class="form-control form-control-sm form-control-line" type="text" placeholder="Choix2" name="Choix2" id="Choix2">
            <br>
            Choix3 <input class="form-control form-control-sm form-control-line" type="text" placeholder="Choix3" name="Choix3" id="Choix3">
            <br>
            Reponse <select class="custom-select col-12" name="Response">
                <option value=1>Choix1</option>
                <option value=2>Choix2</option>
                <option value=3>Choix3</option>
            </select>
            <br>
            <br>
            <br>
            <br>
            <button class="btn btn-outline-primary" type="button" onclick="ControlSaisie()">Ajouter Question</button>
        </form>
    </div>
    </body>
    </html>
    <script>
        function ControlSaisie() {
            var Question = document.getElementById("Question").value;
            var Choix1 = document.getElementById("Choix1").value;
            var Choix2 = document.getElementById("Choix2").value;
            var Choix3 = document.getElementById("Choix3").value;

            if (Question !== "" && Question != null) {
                if (Choix1 != null && Choix1 !== "") {
                    if (Choix2 != null && Choix2 !== "") {
                        if (Choix3 != null && Choix3 !== "") {
                            //c bon
                        } else {
                            alert("Le Champ Choix3 est vide!");
                            return false;
                        }
                    } else {
                        alert("Le Champ Choix2 est vide!");
                        return false
                    }
                } else {
                    alert("Le Champ Choix1 est vide!");
                    return false;
                }
            } else {
                alert("Le Champ Question est vide!");
                return false;
            }
            document.getElementById("form").submit();
            return true;
        }
    </script>
{% endblock %}

sprint1/templates/evaluation/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Liste des Evaluations</h4>

        </div>

    </div>
    <table class="table" >
        <tr class="table-light">
            <th>ID</th>
            <th>Libelle</th>
            <th>Description</th>
            <th>Date</th>
            <th>ID Entreprise</th>
            <th>Modifier</th>
            <th>Supprimer</th>
            <th>Imprimer PDF</th>
        </tr>
        {% for Evaluation in classe %}
            <tr>
                <td>
                    {{Evaluation.ID}}
                </td>
                <td>
                    {{Evaluation.Libelle}}
                </td>
                <td>
                    {{ Evaluation.Description}}
                </td>
                <td>
                    {{ Evaluation.Dateevaluation}}
                </td>
                <td>
                    {{ Evaluation.idEntreprise}}
                </td>
                <td>
                <form action="{{ path('modifierEvaluation',{'id':Evaluation.id} )}}"><button class="btn btn-outline-primary" > Modifier</button></form>
                </td>
                <td>
                    <form action="{{ path('supprimerEvaluation',{'id':Evaluation.id} )}}"><button class="btn btn-outline-primary">Supprimer</button></form>
                </td>
                <td>
                    <form action="{{ path('pdfEvaluation',{'id':Evaluation.id,'libelle':Evaluation.Libelle,'description':Evaluation.description,'dateevaluation':Evaluation.Dateevaluation,'identreprise':Evaluation.idEntreprise} )}}"><button class="btn btn-outline-primary">pdf</button></form>
                </td>


            </tr>
        {% endfor %}


    </table>



{% endblock %}
{#POTFOLIO*********************************************************************************#}

sprint1/templates/evaluation/listF.html.twig
{% extends 'front.html.twig' %}
{% block body %}
    <script src="{{ asset('wiki.js') }}"></script>
    <section id="portfolio" class="portfolio">
        <div class="container">



            <div class="row portfolio-container">
                {% for Evaluation in classe %}
                    {% for ParticipationEvaluation in participation %}
                        {% if (ParticipationEvaluation.idE==Evaluation.id and ParticipationEvaluation.idP==1) %}
                <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
                    <div class="portfolio-wrap">
                        <figure>
                            <img src="evaluation.jpg" class="img-fluid" alt="">
{#                            <a href="assets/img/portfolio/portfolio-1.jpg" data-gallery="portfolioGallery" class="link-preview portfolio-lightbox" title="Preview"><i class="bx bx-plus"></i></a>#}
                            <a href={{ path('participerQuiz',{'id':Evaluation.id} )}} class="link-details" title="More Details"><i>test</i></a>
                        </figure>

                        <div class="portfolio-info">
                            <h4><a href="portfolio-details.html">{{ Evaluation.Libelle }}</a></h4>
                            <p>{{ Evaluation.Description }}</p>
                        </div>
{#                        <div class="text-center">#}
{#                            <div class="d-flex justify-content-center">#}
{#                                <h3 style="color : gray">Wikipedia Search for the term : {{Evaluation.Libelle}}</h3>#}
{#                                <input id="key" name="search" value="{{Evaluation.Libelle}}" hidden>#}


{#                                <div class="articles"></div>#}

{#                            </div>#}
{#                        </div>#}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                {% endfor %}



            </div>

        </div>
    </section><!-- End Portfolio Section -->
{% endblock %}

sprint1/templates/evaluation/listP.html.twig
{% extends 'base.html.twig' %}
{% block body  %}

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4"> Liste des Participations au Evaluation</h4>

        </div>

    </div>
    <table class="table">
        <tr class="table-light">
            <th>Code</th>
            <th>ID Evaluation</th>
            <th>ID Participant</th>
            <th>Note</th>
            <th>Supprimer</th>
        </tr>
        {% for p in classe %}
            {% if (p.idE==idE) %}
            <tr>
                <td>
                    {{p.Code}}
                </td>
                <td>
                    {{p.idE}}
                </td>
                <td>
                    {{p.idP}}
                </td>
                <td>
                    {% if(p.Note)== NULL %} Non Assigné {% endif %}
                </td>
                <td>
                    <form action="{{ path('supprimerParticipationEvaluation',{'code':p.code} )}}"><button class="btn btn-outline-primary">Supprimer</button></form>
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

sprint1/templates/evaluation/listQ.html.twig
{% extends 'base.html.twig' %}
{% block body  %}

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4"> Liste des Questions du Quiz</h4>

        </div>

    </div>
    <table class="table">
        <tr class="table-light">
            <th>ID Evaluation</th>
            <th>ID Quiz</th>
            <th>Question</th>
            <th>Choix1</th>
            <th>Choix2</th>
            <th>Choix3</th>
            <th>Reponse</th>
            <th>Supprimer</th>
        </tr>
        {% for q in classe %}
            {% if (q.idEvaluation==idE) %}
                <tr>
                    <td>
                        {{q.idEvaluation}}
                    </td>
                    <td>
                        {{q.id}}
                    </td>
                    <td>
                        {{q.Question}}
                    </td>
                    <td>
                        {{q.Choix1}}
                    </td>
                    <td>
                        {{q.Choix2}}
                    </td>
                    <td>
                        {{q.Choix3}}
                    </td>
                    <td>
                        Choix{{q.Reponse}}
                    </td>
                    <td>
                        <form action="{{ path('supprimerQuiz',{'id':q.id} )}}"><button class="btn btn-outline-primary">Supprimer</button></form>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

sprint1/templates/evaluation/participants.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Liste des Participants</h4>

        </div>

    </div>
    <table class="table">
        <tr class="table-light">

            <th>ID</th>
            <th>Libelle</th>
            <th>Ajouter Participants</th>
            <th>Afficher Participants</th>

        </tr>
        {% for Evaluation in classe %}
            <tr>
                <td>
                    {{Evaluation.ID}}
                </td>
                <td>
                    {{Evaluation.Libelle}}
                </td>
                <td>
                    <form action="{{ path('ajouterParticipationEvaluation',{'idE':Evaluation.id})}}"><button class="btn btn-outline-primary">Ajouter Participants</button></form>
                </td>
                <td>
                    <form action="{{ path('ListParticipationEvaluation',{'idE':Evaluation.id})}}"><button class="btn btn-outline-primary">Afficher Participants</button></form>
                </td>
            </tr>
        {% endfor %}

    </table>



{% endblock %}

sprint1/templates/evaluation/quiz.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Liste des Quiz</h4>

        </div>

    </div>
    <table class="table">
        <tr class="table-light">

            <th>ID</th>
            <th>Libelle</th>
            <th>Ajouter Question</th>
            <th>Afficher Quiz</th>

        </tr>
        {% for Evaluation in classe %}
            <tr>
                <td>
                    {{Evaluation.ID}}
                </td>
                <td>
                    {{Evaluation.Libelle}}
                </td>
                <td>
                    <form action="{{ path('ajouterQuiz',{'idE':Evaluation.id})}}"><button class="btn btn-outline-primary">Ajouter Question</button></form>
                </td>
                <td>
                    <form action="{{ path('ListQuiz',{'idE':Evaluation.id})}}"><button class="btn btn-outline-primary">Afficher Quiz</button></form>
                </td>
            </tr>
        {% endfor %}

    </table>



{% endblock %}

sprint1/templates/evaluation/quizF.html.twig
{% extends 'front.html.twig' %}
{% block body %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <section id="portfolio" class="portfolio">
    <div class="container">
            {% set cmp=0 %}
                {% for quiz in quiz %}
                    {% if evaluation.id==quiz.idEvaluation %}
                        {% set cmp=cmp+1 %}
                <label class="large-label">Question{{ cmp}} : {{ quiz.Question }}</label><br>
                    <input type="radio"  name="choix{{ cmp }}" value={{ quiz.Choix1 }}>
                    <label>{{ quiz.Choix1 }}</label><br>
                    <input type="radio"  name="choix{{ cmp }}" value={{ quiz.Choix2 }}>
                    <label>{{ quiz.Choix2 }}</label><br>
                    <input type="radio"  name="choix{{ cmp }}" value={{ quiz.Choix3 }}>
                    <label for="choix">{{ quiz.Choix3 }}</label><br>
                    {% endif %}
                {% endfor %}
        <form method="POST">
            <div class="g-recaptcha" data-sitekey="6LezZHoaAAAAADzHuijwpBNJZfKeaydmQaLw25wC"></div>
            <br/>
            <input type="submit" value="Submit">
        </form>
        </body>

    </div>
    </section>

{% endblock %}

sprint1/templates/evaluation/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Modifier Evaluation</title>
</head>
<body>

<br>
<br>
<br>

<div class="pd-20 card-box mb-30">
    <h2>Modifier Evaluation</h2> <br> <br>
    <div class="clearfix">

    </div>
<form action="" method="POST" name="form" id="form">
    Libelle <input class="form-control form-control-sm form-control-line" type="text" placeholder="Libelle" name="Libelle" id="Libelle" value={{ evaluation.Libelle }}>
    <br>
    Description <input class="form-control form-control-sm form-control-line" type="text" placeholder="Description" name="Description" id="Description" value={{ evaluation.Description }}>
    <br>
    Date Evaluation <input class="form-control form-control-sm form-control-line" type="text" placeholder="Date Evaluation" name="Dateevaluation" id="Dateevaluation" value={{ evaluation.Dateevaluation }} readonly>
    <br>
    Id Entreprise <select class="custom-select col-12" name="Identreprise">
        {% for Entreprise in classe %}
            <option value={{ Entreprise.Id }} {% if (Entreprise.Id==evaluation.Identreprise) %} selected {% endif %}>{{ Entreprise.Id }}</option>
        {% endfor %}
    </select>
    <br>
    <br>
    <br>
    <button class="btn btn-outline-primary" type="button" onclick="ControlSaisie()">Modifier Evaluation</button>
</form>
</div>
</body>
</html>
    <script>
        function isValidDate2(dateString)
        {
           /* var parts = dateString.split("-");
            var day = parseInt(parts[1], 10);
            var month = parseInt(parts[0], 10);
            var year = parseInt(parts[2], 10);

            var today = new Date();
            var today_x = today.getFullYear()*10000+(today.getMonth()+1)*100+today.getDate();
            var date_x = year*10000 + month*100 + day;
            return date_x > today_x;*/
            return true;
        }

        function isValidDate(dateString)
        {
            if(!/^\d{1,2}\-\d{1,2}\-\d{4}$/.test(dateString))
                return false;

            var parts = dateString.split("-");
            var day = parseInt(parts[1], 10);
            var month = parseInt(parts[0], 10);
            var year = parseInt(parts[2], 10);

            if(year < 1000 || year > 3000 || month == 0 || month > 12)
                return false;

            var monthLength = [ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 ];

            if(year % 400 == 0 || (year % 100 != 0 && year % 4 == 0))
                monthLength[1] = 29;

            return day > 0 && day <= monthLength[month - 1];
        }
        function ControlSaisie() {
            var Libelle = document.getElementById("Libelle").value;
            var Description = document.getElementById("Description").value;
            var DateE = document.getElementById("Dateevaluation").value;

            if (Libelle !== "" && Libelle != null) {
                if (Description != null && Description !== "") {
                    if (DateE != null && DateE !== "" && isValidDate(DateE) && isValidDate2(DateE)) {
                        //c bon
                    } else {
                        alert("Le Champ Date Evaluation n'est pas valide!");
                        return false;
                    }
                } else {
                    alert("Le Champ Description est vide!");
                    return false
                }
            } else {
                alert("Le Champ Libelle est vide!");
                return false;
            }
            document.getElementById("form").submit();
            return true;
        }
    </script>
{% endblock %}