integration/src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass=OffreRepository::class)
 */
class Offre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string")
     */
    private $Salaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Disponabilite;

    /**
     * @ORM\Column(type="string")
     */
    private $DateLimite;

    /**
     * @ORM\ManyToMany(targetEntity=Utilisateur::class, inversedBy="offres")
     */
    private $utilisateurs;
    /**
     * @ORM\ManyToMany(targetEntity=Utilisateur::class, inversedBy="favoris")
     * @ORM\JoinTable(name="Utilisateur_favoris")
     */
    private $favoris;
    public function __construct()
    {
        $this->favoris = new ArrayCollection();
    }
    /**
     * @return Collection|Utilisateur[]
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Utilisateur $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
        }

        return $this;
    }

    public function removeFavori(Utilisateur $favori): self
    {
        $this->favoris->removeElement($favori);

        return $this;
    }

//    /**
//     * @ORM\ManyToMany(targetEntity=Postulant::class, inversedBy="favoris")
//     * @ORM\JoinTable(name="postulant_favoris")
////     */
//    private $favoris;
//
//    public function __construct()
//    {
//        $this->favoris = new ArrayCollection();
//    }
    public function getUtilisateurs(): Collection
    {
        return $this->utilisateurs;
    }
    public function addUtilisateur(Utilisateur $utilisateur): self
    {
        if (!$this->utilisateurs->contains($utilisateur)) {
            $this->utilisateurs[] = $utilisateur;
        }

        return $this;
    }

    public function removeUtilisateur(Utilisateur $utilisateur): self
    {
        $this->utilisateurs->removeElement($utilisateur);

        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSalaire(): ?string
    {
        return $this->Salaire;
    }

    public function setSalaire(string $Salaire): self
    {
        $this->Salaire = $Salaire;

        return $this;
    }

    public function getDisponabilite(): ?string
    {
        return $this->Disponabilite;
    }

    public function setDisponabilite(string $Disponabilite): self
    {
        $this->Disponabilite = $Disponabilite;

        return $this;
    }

    public function getDateLimite(): ?string
    {
        return $this->DateLimite;
    }

    public function setDateLimite(string $DateLimite): self
    {
        $this->DateLimite = $DateLimite;

        return $this;
    }

//    /**
//     * @return Collection|Postulant[]
//     */
//    public function getPostulants(): Collection
//    {
//        return $this->postulants;
//    }
//
//    public function addPostulant(Postulant $postulant): self
//    {
//        if (!$this->postulants->contains($postulant)) {
//            $this->postulants[] = $postulant;
//        }
//
//        return $this;
//    }
//
//    public function removePostulant(Postulant $postulant): self
//    {
//        $this->postulants->removeElement($postulant);
//
//        return $this;
//    }
//
//    /**
//     * @return Collection|Postulant[]
//     */
//    public function getFavoris(): Collection
//    {
//        return $this->favoris;
//    }
//
//    public function addFavori(Postulant $favori): self
//    {
//        if (!$this->favoris->contains($favori)) {
//            $this->favoris[] = $favori;
//        }
//
//        return $this;
//    }
//
//    public function removeFavori(Postulant $favori): self
//    {
//        $this->favoris->removeElement($favori);
//
//        return $this;
//    }

}

integration/templates/postulant/a.html.twig
{% extends 'jamel1.html.twig' %}
{% block body %}
    <h4>Inscription Evenements</h4>
    <br><br><br>
    <table id="bootstrap-data-table"class="table" >

        <th>Nom</th>
        <th>Prénom</th>

        <th>Email</th>


        </tr>
        {% for Post in post %}
            <tr>

                <td>
                    {{Post.nomPersonne}}
                </td>
                <td>
                    {{Post.prenomPersonne}}
                </td>
                <td>
                    {{ Post.email}}
                </td>

                <td>
                    <form ><button  class="btn btn-outline-info"><h6>Send Mail</h6></button></form>
                </td>


            </tr>
        {% endfor %}
    </table>

{% endblock %}

integration/templates/postulant/add.html.twig
{% extends 'jamel1.html.twig' %}
 {% block content %}  {% endblock  %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajouter votre participation </title>
</head>
<body>
<h1>votre information de participation</h1>
<br>
<form action="" method="POST">
    Nom: <input type="text" placeholder="Email" name="Email" value="{{ user.nomPersonne }}">
    Prenom: <input type="text" placeholder="Email" name="Email" value="{{ user.prenomPersonne }}">


    Email: <input type="text" placeholder="Email" name="Email" value="{{ user.email }}">


    <button type="submit" class="btn btn-primary btn-sm">submit</button>
</form>
</body>
</html>
{% endblock %}

integration/templates/postulant/add1.html.twig
{% extends 'jamel2.html.twig' %}
 {% block content %}  {% endblock  %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>ajouter participation</title>
    </head>
    <body>
    <h1>Créer une nouvelle Post</h1>
    <form action="" method="POST">
                Nom: <input type="text" placeholder="Nom" value="{{ user.nomPersonne }}">
                Prenom: <input type="text" placeholder="Prenom"  value="{{ user.prenomPersonne }}">
{#        Sexe: <input type="text" placeholder="Prenom" name="sex">#}
{#                EtatScosial: <input type="text" placeholder="EtatScolaire" name="etatSocialePersonne">#}
{#        telephone: <input type="text" placeholder="Adresse" name="telephone">#}
{#                Date de naissance: <input type="date" placeholder="DateNais" name="DateNais">#}
{#                Telephone: <input type="text" placeholder="Telephone" name="Telephone">#}
{#                Status:#}
{#                <p>#}
{#                    Marié(e) <input type="radio" placeholder="Status" name="Status" value="Marié(e)">#}
{#                    Célibaire <input type="radio" placeholder="Status" name="Status" value="Célibaire">#}
{#                </p>#}
{#                Competences: <input type="text" placeholder="Competences" name="Competences">#}
        Email: <input type="text" placeholder="Email" value="{{ user.Email }}" name="Email">


        <button type="submit" class="btn btn-primary btn-sm">submit</button>
    </form>
    </body>
    </html>
{% endblock %}

integration/templates/postulant/fav.html.twig
{% extends 'firas1.html.twig' %}
 {% block content %}  {% endblock  %}
{% block body %}
    <div class="page-content">

    <section id="blog" class="content-section" style="width: 1100pt" >
        <div class="section-heading" >
            <strong> <h1>Liste des<em>        Favoris</em></h1> </strong>
        </div>

        <div class="section-content" style="margin-right:50px" >
            <div class="tabs-content" style="margin-top:0px">
                <div class="wrapper">
                    <ul class="tabs clearfix" data-tabgroup="first-tab-group">
                        <li><a href="#tab1" class="active">1</a></li>
                        <li><a href="#tab2">2</a></li>
                        <li><a href="#tab3">3</a></li>
                        <li><a href="#tab4">4</a></li>
                    </ul>
                    {% for offre in fav %}
                        <section id="first-tab-group" class="tabgroup">
                            <div id="tab1">
                                <ul>
                                    <li>
                                        <div class="item">
                                            <img src="img/blog_2.jpg" alt="">
                                            <div class="text-content">
                                                <h4> {{offre.libelle}}</h4>
                                                <span>{{ offre.DateLimite}}</span>
                                                <p>{{ offre.description}}</p>

                                                <div class="accent-button button">
                                                    <form action="{{ path('ajoutPost',{'id':offre.id} )}}"><button  class="btn btn-outline-info"><h7>Participer</h7></button></form>
                                                </div>
                                            </div>
                                        </div>
                                    </li>

                                </ul>
                            </div>


                        </section>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="js/vendor/bootstrap.min.js"></script>

    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

    <script>
        // Hide Header on on scroll down
        var didScroll;
        var lastScrollTop = 0;
        var delta = 5;
        var navbarHeight = $('header').outerHeight();

        $(window).scroll(function(event){
            didScroll = true;
        });

        setInterval(function() {
            if (didScroll) {
                hasScrolled();
                didScroll = false;
            }
        }, 250);

        function hasScrolled() {
            var st = $(this).scrollTop();

            // Make sure they scroll more than delta
            if(Math.abs(lastScrollTop - st) <= delta)
                return;

            // If they scrolled down and are past the navbar, add class .nav-up.
            // This is necessary so you never see what is "behind" the navbar.
            if (st > lastScrollTop && st > navbarHeight){
                // Scroll Down
                $('header').removeClass('nav-down').addClass('nav-up');
            } else {
                // Scroll Up
                if(st + $(window).height() < $(document).height()) {
                    $('header').removeClass('nav-up').addClass('nav-down');
                }
            }

            lastScrollTop = st;
        }
    </script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>

{% endblock %}

integration/templates/postulant/index.html.twig
{% extends 'jamel1.html.twig' %}

{% block title %}Hello PostulantController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/21652/Documents/GitHub/CodeBrigade/mydir/src/Controller/PostulantController.php'|file_link(0) }}">src/Controller/PostulantController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/21652/Documents/GitHub/CodeBrigade/mydir/templates/postulant/index.html.twig'|file_link(0) }}">templates/postulant/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

integration/templates/postulant/index2.html.twig
{% extends 'firas2.html.twig' %}
 {% block content %}  {% endblock  %}
{% block body %}
    <div class="page-content">

    <section id="blog" class="content-section" style="width: 1100pt" >


        <div class="section-content" style="margin-right:50px" >
            <div class="tabs-content" style="margin-top:0px">
                <div class="wrapper">
                    <ul class="tabs clearfix" data-tabgroup="first-tab-group">
                        <li><a href="#tab1" class="active">1</a></li>
                        <li><a href="#tab2">2</a></li>
                        <li><a href="#tab3">3</a></li>
                        <li><a href="#tab4">4</a></li>
                    </ul>
                    {% for offre in class %}
                        <section id="first-tab-group" class="tabgroup">
                            <div id="tab1">
                                <ul>
                                    <li>
                                        <div class="item">
                                            <img src="img/blog_2.jpg" alt="">
                                            <div class="text-content">
                                                <h4> {{offre.libelle}}</h4>
                                                <span>{{ offre.DateLimite}}</span>
                                                <p>{{ offre.description}}</p>

                                                <div class="accent-button button">
                                                    <form action="{{ path('ajoutPost',{'id':offre.id} )}}">
                                                        <button  class="btn btn-outline-info"><h7>Participer</h7>
                                                        </button></form>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="accent-button button">
                                            <form action="{{ path('ajoutFav',{'id':offre.id} )}}">
                                                <button  class="btn btn-outline-info"><h7>Ajouter aux Favoris</h7>
                                                </button></form>
                                        </div>
                                    </li>

                                </ul>
                            </div>


                        </section>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="js/vendor/bootstrap.min.js"></script>

    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

    <script>
        // Hide Header on on scroll down
        var didScroll;
        var lastScrollTop = 0;
        var delta = 5;
        var navbarHeight = $('header').outerHeight();

        $(window).scroll(function(event){
            didScroll = true;
        });

        setInterval(function() {
            if (didScroll) {
                hasScrolled();
                didScroll = false;
            }
        }, 250);

        function hasScrolled() {
            var st = $(this).scrollTop();

            // Make sure they scroll more than delta
            if(Math.abs(lastScrollTop - st) <= delta)
                return;

            // If they scrolled down and are past the navbar, add class .nav-up.
            // This is necessary so you never see what is "behind" the navbar.
            if (st > lastScrollTop && st > navbarHeight){
                // Scroll Down
                $('header').removeClass('nav-down').addClass('nav-up');
            } else {
                // Scroll Up
                if(st + $(window).height() < $(document).height()) {
                    $('header').removeClass('nav-up').addClass('nav-down');
                }
            }

            lastScrollTop = st;
        }
    </script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>

{% endblock %}

integration/templates/postulant/list.html.twig
{% extends 'firas1.html.twig' %}
{% block body %}

    <table class="table">
        <tr class="table-light">
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Sexe</th>
            <th scope="col">Etat Sociale</th>
            <th scope="col">Adresse</th>

            <th scope="col">Email</th>
            <th scope="col">Compétence</th>
        </tr>
        {% for Post in post %}
            <tr>
                <td>
                    {{Post.nomPersonne}}
                </td>
                <td>
                    {{Post.prenomPersonne}}
                </td>
                <td>
                    {{ Post.sexePersonne}}
                </td>
                <td>
                    {{ Post.etatSocialePersonne}}
                </td>
                <td>
                    {{ Post.adresse}}
                </td>
                <td>
                    {{ Post.email}}
                </td>
                <td>
                    {{ Post.domainePersonne}}
                </td>
                <td>
                    <a class="btn btn-success" href="{{ path('rendezvous',{'id':Post.id})}}">Accepter</a>
                </td>
                <td>
                    <form  action="{{ path('suppPost',{'id':Post.id})}}"><button type="submit" class="btn btn-danger"> supprimer</button></form>
                </td>

            </tr>
        {% endfor %}
    </table>
{% endblock %}